language: node_js
node_js:
- "7"
- "8"
- "9"
- "lts/*"
- "node"
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_9c8b27f7c340_key -iv $encrypted_9c8b27f7c340_iv
  -in .env.enc -out .env -d
deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
      node_js: "lts/*"